server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
    
spring.social.twitter.appId: ogIANEpF2RkLxvHrzO0Cu5sVi
spring.social.twitter.appSecret: UbOselGMS6lmGQrey3NsjxO231UzWfOG8akh7Nhc6wbbxtBMQE

logging:
  level:
    ROOT: INFO

#mail:
#  host: localhost
#  port: 2525
#  username: testsocialfocus@gmail.com
#  password: user123social
#  properties:
#    starttls.enable: true
#    mail.smtp.auth: true
#    mail.smtp.starttls.enable: true
#    mail.smtp.starttls.required: true
#  logging:
#    enabled: true
#    strategy:
#      from: PLAIN_TEXT
#      replyTo: HIDDEN
#      to: FULL_TEXT_FROM_COMMERCIAL_AT
#      cc: HIDDEN
#      bcc: HIDDEN
#      subject: PLAIN_TEXT
#      body: FIRST_DOZEN_THEN_STARS
#      attachments: HIDDEN
#      encoding: HIDDEN
#      locale: HIDDEN
#      sentAt: STANDARD_DATE_FORMAT_WITH_ZONE_ID
#      receiptTo: HIDDEN
#      depositionNotificationTo: HIDDEN
#      ignore.customHeaders: true
#      ignore.nullAndEmptyCollections: true





spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: false
spring.mail.properties.mail.smtp.starttls.required: false

spring.mail.host: 10.150.1.19
spring.mail.port: 25
spring.mail.username: notifier@socialfocus.com.ar
spring.mail.password: 

emailCustom.emailSender: "notifier@socialfocus.com.ar"
emailCustom.emailSenderDescription: "Equipo de cuentas SocialFocus"
emailCustom.notificationTitle: "Confirmación de seguridad de la cuenta SocialFocus"

token.expiration: 1


#spring.mail.logging.enabled: true
#
#spring.mail.logging.strategy.from: PLAIN_TEXT
#spring.mail.logging.strategy.replyTo: HIDDEN
#spring.mail.logging.strategy.to: FULL_TEXT_FROM_COMMERCIAL_AT
#spring.mail.logging.strategy.cc: HIDDEN
#spring.mail.logging.strategy.bcc: HIDDEN
#spring.mail.logging.strategy.subject: PLAIN_TEXT
#spring.mail.logging.strategy.body: FIRST_DOZEN_THEN_STARS
#spring.mail.logging.strategy.attachments: HIDDEN
#spring.mail.logging.strategy.encoding: HIDDEN
#spring.mail.logging.strategy.locale: HIDDEN
#spring.mail.logging.strategy.sentAt: STANDARD_DATE_FORMAT_WITH_ZONE_ID
#spring.mail.logging.strategy.receiptTo: HIDDEN
#spring.mail.logging.strategy.ignore.customHeaders: true
#spring.mail.logging.strategy.depositionNotificationTo: HIDDEN
#spring.mail.logging.strategy.ignore.nullAndEmptyCollections: true

  